# Generated by Django 2.2.7 on 2020-06-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200627_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='idno',
        ),
    ]
