# Generated by Django 2.2.7 on 2020-06-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200627_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='vote_from',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='vote_from',
            field=models.TextField(),
        ),
    ]
