# Generated by Django 2.2.7 on 2020-06-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200628_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrib',
            old_name='fromm',
            new_name='scrib_from',
        ),
        migrations.AlterField(
            model_name='tag',
            name='vote_from',
            field=models.CharField(max_length=200),
        ),
    ]
