# Generated by Django 2.2.7 on 2020-06-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200628_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='vote_from',
            field=models.TextField(),
        ),
    ]
